leftnav:
- identifier: f64ad22f-3f59-4d9b-a56b-b0c786d884ec
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 9b20f753-2bf1-44ca-8de7-f6408b422d71
  name: Assignments
  url: /pages/assignments
  weight: 20
- identifier: f2ec91d8-3e29-4484-8032-8b66ede72d23
  name: Exams
  url: /pages/exams
  weight: 30
